#ifndef NGIFRAMEWORK_GLOBAL_H
#define NGIFRAMEWORK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NGIFRAMEWORK_LIBRARY)
#  define NGIFRAMEWORKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NGIFRAMEWORKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NGIFRAMEWORK_GLOBAL_H
