#ifndef NGIESTIMATORS_GLOBAL_H
#define NGIESTIMATORS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NGIESTIMATORS_LIBRARY)
#  define NGIESTIMATORSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NGIESTIMATORSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NGIESTIMATORS_GLOBAL_H
