#ifndef NGIPREPROCESSING_GLOBAL_H
#define NGIPREPROCESSING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NGIPREPROCESSING_LIBRARY)
#  define NGIPREPROCESSINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NGIPREPROCESSINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NGIPREPROCESSING_GLOBAL_H
